### ISSUE TITLE
Add support for belt 

### ISSUE THREAD

**Issue by amiralies** [reason-association/reanalyze#111]

**Comment by cristianoc** [comment]
Would you elaborate on the title of this issue?

**Comment by amiralies** [comment]
My bad. I meant exception analysis for belt standard library. eg. Belt.Map.getExn

**Comment by cristianoc** [comment]
Here's a template adding `Belt.Map` and `Belt.List`: https://github.com/reason-association/reanalyze/pull/112
The template includes the various aliases, such as e.g. `Belt_Map`. In theory these are not documented, but there's nothing stopping people from using them directly.

Other parts of Belt can be added in the same way, though it does not need more tests, those are only there to check that the mechanism works.

**Comment by cristianoc** [comment]
Merged.
