### ISSUE TITLE
Read annotation in doc comment for exception

### ISSUE THREAD

**Issue by Et7f3** [reason-association/reanalyze#54]
Ocamldoc has special annotation `@raise Invalid_argument` that we can add in the doc comment.
And when building the doc we can see it. A example of the stdlib https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html#VALinit and in the code https://github.com/ocaml/ocaml/blob/trunk/stdlib/list.mli#L82. We can see that the Exception is highlighted in the generated html.

Atm reanalyze support only `[@raise ]` in the implementation file as attribute so it is not read by ocamldoc. It would be convenient if reanalyze could read doc comment and suggest to add in the comment. This way it help us to write good comment.

**Comment by cristianoc** [comment]
@Et7f3 one issue with doc comments is how to read them from libraries.
In the case of bucklescript, libraries are in a conventional place.
But in the case of native, libraries are wherever the build system looks for them (dune, or dune + esy), and it would be complex to replicate the same logic here.

**Comment by Et7f3** [comment]
> one issue with doc comments is how to read them from libraries.

```
# (*comment*);;
# (**comment*);;
Ptop_def
  []
Ptop_def
  [
    structure_item (//toplevel//[1,0+0]..[1,0+12])
      Pstr_attribute "ocaml.text"
      [
        structure_item (//toplevel//[1,0+0]..[1,0+12])
          Pstr_eval
          expression (//toplevel//[1,0+0]..[1,0+12])
            Pexp_constant PConst_string("comment",None)
      ]
  ]
```

We can see that doc comment are preserved in the ast.

if comment are in interface file: then their is a .cmti/.cmi next to the implementation corresponding .cmt/.cmo.

> it would be complex to replicate the same logic here.

So the logic is quite simple (remove the 'o' if it is last char and add 'i')

**Comment by cristianoc** [comment]
I think what's possible is a bootstrapping process, where doc comments can be used as a starting point. However, some manual tweaking has already been necessary:

```reason
    ("blit_string", [invalidArgument]),
    // ("concat", [invalidArgument]), if longer than {!Sys.max_string_length}
    // ("cat", [invalidArgument]), if longer than {!Sys.max_string_length}
    // ("escaped", [invalidArgument]), if longer than {!Sys.max_string_length}
    ("index", [notFound]),
```

where the commented-out functions would lead to mostly noise.
